### ISSUE TITLE
FinCEN Suspicious Activity Report

### ISSUE THREAD

**Issue by evgenydmitriev** [1712n/challenge#61]
BuzzFeed and their partners released stories about a trove of almost 2,500 Suspicious Activity Reports (SARs) filed by banks with the Financial Crimes Enforcement Network (FinCEN) between 2000 and 2017. They included thousands of suspicious bank transactions totaling over $35B. In cooperation with BuzzFeed, the International Consortium of Investigative Journalists (ICIJ) published a dataset that includes detailed information on 4500 suspicious transactions. There's evidence that some leaked SARs involve cryptocurrency-related activity.

![image](https://user-images.githubusercontent.com/56804873/131855900-b091535d-5c61-408d-bd6f-b4e5c8846ac4.png)

For example, on January 15, 2016, $1M was moved from the Bank of China’s account to Saigon Thuong Tin Commercial Joint Stock Bank, a Vietnam-based financial institution. One day prior to that, on January 14, 2016, a transfer of approximately the same amount ($1,003,862.21061 at the time) was spotted on Bitcoin blockchain to 3HNSiAq7wFDaPsYDcUxNSRMD78qVcYKicw address. This address received funds from a drained Cryptsy hot wallet, a now defunct cryptocurrency trading platform. Cryptsy’s CEO Paul Vernon claimed this was due to a hack, but was accused of stealing customer funds and is facing a class action lawsuit.

Try finding other suspiciously similar transactions using datasets listed below. You can use any tools/methods. Feel free to support your findings with datasets, graphs, and method description.

### Datasets
Request access to datasets if you don't have it.
- [FinCEN SAR dataset](https://www.icij.org/investigations/fincen-files/download-fincen-files-transaction-data/)
- [Large Bitcoin blockchain transactions](https://drive.google.com/file/d/13mUDfarRMNjHBLe71lwcx_CgFa-kM5e5/view?usp=sharing)
- [Bitcoin-USD historical pricing](https://drive.google.com/drive/folders/1KI-PCxdM18cy9t8bAQ1VDjltZb1m2rAI?usp=sharing)

### Additional Resources

* [Challenge Program Wiki](https://github.com/1712n/challenge)
* [List of available tasks](https://github.com/1712n/challenge/issues)
* [Inca Digital website](https://inca.digital)

Please email challenge-submission@blockshop.org with your solution, and don't forget to include a link to this issue and attach your resume. Don't hesitate to ask us questions by commenting in this issue or emailing us at challenge-program@blockshop.org

### Successful submissions

🎉 @NikitaZah solved the challenge and got hired by @inca-digital

**Comment by SergeKachkovskiy** [comment]
Hi! Sent you my thoughts right now by e-mail

**Comment by aleksanderbachinin** [comment]
Hey,
I've sent you my findings by email.

**Comment by VeronikaShelkovina** [comment]
Hi!
I have sent you my results by e-mail

**Comment by mandayamr** [comment]
Hi,
I have sent my findings by e-mail

**Comment by KhurazovRuslan** [comment]
Sent my solution via e-mail
ruslan.khurazov@gamil.com

**Comment by evgenydmitriev** [comment]
🎉 @NikitaZah solved the challenge and got hired by @inca-digital 🍾 Congrats 🍾
