### ISSUE TITLE
Flag GitHub issues

### ISSUE THREAD

**Issue by evgenydmitriev** [1712n/challenge#63]
We often come across situations when people unintentionally share sensitive information in GitHub Issue Tracker, such as names of clients or details of active investigations. Provide links to 2-3 tools you would use to automatically flag comments with sensitive content in our GitHub issue tracker.

### Additional Resources

* [Challenge Program Wiki](https://github.com/1712n/challenge/)
* [List of available tasks](https://github.com/1712n/challenge/issues)
* [Inca Digital website](https://inca.digital)

Please email challenge-submission@blockshop.org with your solution, and don't forget to include a link to this issue and attach your resume. Don't hesitate to ask us questions by commenting in this issue or emailing us at challenge-program@blockshop.org

---
### Successful submissions

🎉 @ingakaspar successfully solved the challenge and was hired by Inca Digital. 

---
The challenge is still open. We are removing comments with correct answers to allow others to participate, so it is safe to assume that the answers listed below are incorrect.

**Comment by SergyKo** [comment]
You can create an array of data with confidential names in the form key => value, leave the keys in the repository, and transfer the bundle separately and restore full data through a script or regular expressions.

**Comment by elviranasirova** [comment]
git filter-repo tool and the BFG Repo-Cleaner

**Comment by AliceFender** [comment]
There are some softwares for scanning committed secrets in repositories in Github. 
Namely: GitSecrets, Trufflehog, GitHound and many others. Two below 
have alerts: 

Git Guardian
https://www.gitguardian.com/
Secret Scanning
https://github.com/KainosSoftwareLtd/secret-scanning

**Comment by anastasiasafargalieva** [comment]
Credential Digger https://github.com/SAP/credential-digger
Gittyleaks
Repo Supervisor

**Comment by olga-sokolovskaya** [comment]
SpectralOps https://spectralops.io
Whispers https://github.com/Skyscanner/whispers
GitGuardian https://www.gitguardian.com

**Comment by maximkondrushin** [comment]
Hi, is there a chance some of the links mentioned in the comments that are to be assumed incorrect are correct?

**Comment by evgenydmitriev** [comment]
Everything mentioned above is not addressing the stated problem.

**Comment by maximkondrushin** [comment]
GitMonitor https://gitmonitor.com/
Nightfall https://nightfall.ai/

**Comment by maximkondrushin** [comment]
Gitrob

**Comment by annamalakhova777** [comment]
GitRob
Truffle Hog
git-secrets

**Comment by NataliaKramar** [comment]
GitRob
TruffleHog

**Comment by mike-ralenko** [comment]
Hi. Guess these tools should be able to automatically detect what is sensitive content and what is not. But the issues are always diffeent thus the tool should eiher contain information about all possibly sensitive content in the world or be instructed every  time the new issue is taken. The first case seems to be a future of the artifical intelligence (not shure if a nearest one), the second renders the method to manual rather than automatical as per challenge conditions. So there are no tools to solve the task and no relevant links could be provided accordingly.

**Comment by Ta-nu-ki** [comment]
I believe this is a quite faulty approach to post issues and commentaries with potentially sensitive information on the issue tracker such as Github (without pre-moderation function or user groups access restriction rules).
But if Github is must and "how to post a new issue" instructions are thoroughly written and read, next step is to use the GitHub Actions workflow.
https://github.com/marketplace/actions/regex-issue-labeler

**Comment by evgenydmitriev** [comment]
@Ta-nu-ki could you reach out to us at challenge@inca.digital?

**Comment by Prokopajte** [comment]
Hi there! I would use Microsoft Azure Information Protection and Microsoft PowerShell tools.
Thank you for this interesting challenge!

**Comment by Chikrovi** [comment]
Hello, I would use GitMonitor or GitGraber as they offer real-time monitoring to find sensitive data.
Regards

**Comment by AktRus** [comment]
GitMonitor 
Git-secrets

**Comment by XeniyaO** [comment]
SEDATED: https://github.com/OWASP/SEDATED
confidential information in images: https://github.com/DhilipSanjay/Detection-of-Sensitive-Data-Exposure-in-Images
GitMAD: https://github.com/deepdivesec/GitMAD
DataDefender: https://github.com/armenak/DataDefender
SMB-Data-Discovery: https://github.com/gh0x0st/SMB-Data-Discovery

**Comment by JaneBrains** [comment]
ccsrch (PANs): https://sourceforge.net/projects/ccsrch/ 
passhunt: https://pythonrepo.com/repo/Viralmaniar-Passhunt-python-administrative-interfaces

**Comment by DavidOsipov** [comment]
1. https://github.com/marketplace/actions/pii-detection --- this tool is more suitable for your purposes to locate PII in PR and Issues and flag them. At the same time, I'm curious whether the Limitations of the tool would be an issue for your company.
2. https://www.polymerhq.io/github/ -- as you’re dealing with financial and banking info, I think this tool would be of use, because it's pretrained for Baking info search, PII.
3. https://github.com/marketplace/watchtower-radar  --- seems like a good fit tool for your purposes, but I'm not sure whether it will scan for sensitive data in the Issues Tracker

**Comment by ana-k-2020** [comment]
[gitleaks ](https://github.com/zricethezav/gitleaks)
mb: [gitmonitor](https://github.com/Talkaboutcybersecurity/GitMonitor)
[git-secrets](https://github.com/awslabs/git-secrets)

**Comment by ZahirNikmal** [comment]
https://github.com/SAP/credential-digger.git
https://github.com/awslabs/git-secrets.git

**Comment by SwordForShinobi** [comment]
I would do it like this (using regex):

import re

reg_expr = r'[A-Z]\w+\s+[A-Z]\w+|[А-Я]\w+\s+[А-Я]\w+' # regex for 1st and last names (both latin and cyrillic)
re.sub(reg_expr, '', text) # here we simply remove samples matching our regex from text

If you wanna flag them:

def first_and_last_names_filter(text):
  reg_expr = r'[A-Z]\w+\s+[A-Z]\w+|[А-Я]\w+\s+[А-Я]\w+' 
  nameregex = re.compile(reg_expr) 
  names = nameregex.findall(text)
  return names

Additionally, you can add to reg_ex: '|[#\d%\d]' this will delete from text any digits start from # (numbers) and digits end with % (percents). It's just an example.

For complex cases in flaggind sensetive data info I'd use:
I would also suggest using regex, as soon as answers with GitHub repos considered as incorrect  =)

**Comment by sndwhl** [comment]
https://radar.nightfall.ai
https://git-scm.com/docs/git
https://github.com/hashicorp/terraform

**Comment by evgenydmitriev** [comment]
@ingakaspar successfully solved the challenge and was hired by Inca Digital! Congrats 🎉

The challenge is still open. No need to repeat what has been posted above. None of the submissions address the problem stated in the issue description.

**Comment by lunevaalex** [comment]
Kaggle https://www.kaggle.com/datasets
NLTK https://www.nltk.org/

bugcrowd  https://www.bugcrowd.com/
gitrob  https://github.com/michenriksen/gitrob

**Comment by Edgrudskiy** [comment]
Git Monitor https://github.com/Talkaboutcybersecurity/GitMonitor
TruffleeHog https://github.com/trufflesecurity/trufflehog

**Comment by AESosnovsky** [comment]
Hi! submitted the assignment, hope it'll get your interest

**Comment by ozomari** [comment]
1) dtSearch 

https://www.dtsearch.com/

2) Gretel ToolKit

https://gretel.ai/synthetics

3) Pagefreezer 

https://www.pagefreezer.com/monitoring-data-loss-prevention/

**Comment by evgenydmitriev** [comment]
The challenge is still open. No need to repeat what has been posted above. None of the submissions address the problem stated in the issue description.

**Comment by AESosnovsky** [comment]
Hi,
Is there any possibility to get the result of the assignment? Does the absence of an answer mean a refusal?
Thank you

**Comment by SwordForShinobi** [comment]
Hi! I dont actualy get your point, sorry. What assignment? 
--
Отправлено из Mail.ru для Android среда, 12 октября 2022г., 02:34 +07:00 от AESosnovsky  ***@***.*** :

**Comment by AESosnovsky** [comment]
Never mind, I accidentally wrote it here
King regards,
Alex
