### ISSUE TITLE
Geographic NER in Twitter Bios

### ISSUE THREAD

**Issue by evgenydmitriev** [1712n/challenge#65]
This challenge is about Geographic [Named Entity Recognition](https://en.wikipedia.org/wiki/Named-entity_recognition) for our [Twitter Bio Location Dataset](https://github.com/1712n/challenge/blob/master/geographic-ner/Twitter-Bio-Location.txt). We use this dataset to measure the effectiveness of our geotagging tools against the baseline, which can be generated by running the latest version of [geopy](https://github.com/geopy/geopy). 

To participate in the challenge, submit a pull request to this repository that replaces values predicted by geopy with your solution's results. Expanding the pull request description with your methodology can help us better understand your reasoning and evaluate your submission faster. To make sure your submission doesn't get lost, you can also email your pull request link along with your resume and the link to this challenge to [challenge-submission@blockshop.org](mailto:challenge-submission@blockshop.org). Also, don't hesitate to ask us questions by commenting in this issue.

**Comment by alteest** [comment]
It's not clear what to do for this task. Detect NER from sentence (I suppose not)? geopy just send requests to external resources and not clear which part shoud be better-then-geopy? Detect location from lat/long?

**Comment by nlptechbook** [comment]
``Just completed the challenge: 

https://colab.research.google.com/drive/1ggTM5wyJG7IYN90ubUeIFC1_Rvz8Susg?usp=sharing

**Comment by nlptechbook** [comment]
Although the model I mentioned in the previous comment (https://colab.research.google.com/drive/1ggTM5wyJG7IYN90ubUeIFC1_Rvz8Susg?usp=sharing) provides a high level of accuracy (99.5+) against the test set, it still uses a single input sequence (a sequence of words) to make a prediction (a sequence of corresponding NER-labels). To achieve a better accuracy - especially when it comes to identifying geo-entities that have been previously unseen by the model - you might use additional input sequences (so called covariates), such as part-of-speech tags of the words in the input sequence and/or syntactic heads of the words in the sequence, and so on. I've implemented a model that allows using such covariates, and I can provide the code. Please look at the model provided in my previous comment first.

**Comment by nlptechbook** [comment]
The model I built in this colab:  https://colab.research.google.com/drive/1jieTeM6LPZGDZFZ7TP_d86jxKU_WhyMM?usp=sharing relies on syntactic dependency analysis and uses three input sequences to identify geo-entities. A significant part of the code in the beginning is specific to preprocessing the Kaggle NER dataset. So, if you use your own dataset, you definitely won't need this part.

Make sure to play with the sample sentences provided in the end of the colab to figure out how good the model is in determining geo-NERs depending on the context (words surrounding a potential geo-NER), especially when it comes to determining previously unseen entities.

**Comment by nlptechbook** [comment]
You can use our own dataset, but the model I provided should show good
results. It is really context-depended and shows adequate results even
for previously unseen entities. As you might see in the provided
colab, it interprets word Rongo differently in different sentences.

**Comment by alinapark** [comment]
Thank you both! Coordinating in emails

**Comment by avarsenev** [comment]
Hi! Please see my code here: https://github.com/avarsenev/INCA/blob/5277dc9689a96ba40c3b17a001ce0ab6201bff46/NLP_Inca_twilocations_fin.ipynb. I suggest using spacy's GPE labels as a way to dismiss a good chunk of nongeopolitical locations present in the data.

**Comment by shell-escape** [comment]
Could you please clarify the criteria by which we consider an entity to be a geolocation? Some of the records in the twitter dataset are quiet ambiguous, and it is difficult to tell if a record contains or is a geolocation without any context. For example, "DC" could mean Washington, comics or something else. How should such cases be handled?

**Comment by evgenydmitriev** [comment]
@shell-escape, it's up to you what probability threshold you want to establish and how to handle outright junk. No hard requirements there.

**Comment by nlptechbook** [comment]
I'm working out the approach based on discovering and using trends in BERT embeddings to catch context-dependent semantics. The approach can be applied (adapted) to a range of classification NLP tasks, including the one being discussed here. I described the idea in simple terms on my GitHub at https://github.com/nlptechbook/BERTembeddings. There is also a Colab (https://colab.research.google.com/drive/1k_R1qOS79auwS2JEJ7D1mYMXHXad29fd?usp=sharing) and a summary (in Russian) in this Notion doc: https://www.notion.so/BERT-746b8ac8e4fc47b8bef707eabed14aa3
