### ISSUE TITLE
Collect App Reviews

### ISSUE THREAD

**Issue by christina-tkach** [1712n/challenge#69]
The goal of this issue is to collect a minimum of 1000 reviews for any 10 cryptocurrency-related applications (100 each). These could be the apps of the blockchain wallets, crypto custodians, or any crypto projects. 

1. Collect reviews for the apps of your choice and make sure that you define where the reviews are coming from - Apple App Store or Google Play Store. 
2. Identify sentiment score for each review using one of the existing sentiment analysis tools.
3. Identify either geolocation, or language for each review.
4. For the final deliverable, create:

- CSV-file with the following structure: `app name` `username` `timestamp` `app review text` `sentiment score` `country (language)` `marketplace`*

*`marketplace` - Apple App Store or Google Play Store

- short report with graphs (based on the reviews that you collected) and basic descriptive statistics

### Additional Resources

* [Challenge Program Wiki](https://github.com/1712n/challenge/)
* [List of available tasks](https://github.com/1712n/challenge/issues)
* [Inca Digital website](https://inca.digital)

Please email challenge-submission@blockshop.org with your solution, and don't forget to include a link to this issue and attach your resume. Don't hesitate to ask us questions by commenting in this issue or emailing us at challenge-program@blockshop.org

**Comment by valerikache** [comment]
I'm done.

**Comment by valerikache** [comment]
Hi! Is this issue still relevant? I sent a message a week ago but didn't get a response :(

**Comment by evgenydmitriev** [comment]
Hey @valerikache, we saw your email and will reach out later this week. Sorry for the delay! @christina-tkach @alinapark @marina-chibizova

**Comment by mariiatarasova** [comment]
I'm done

**Comment by ChandlerProvence** [comment]
Good evening, I have submitted the requested CSV to the provided email. Thank you for your time and consideration.

**Comment by KY-39** [comment]
I'm done, nice task.😏

**Comment by Ruukes** [comment]
I'm done! Thanks

**Comment by MarkAvilin1** [comment]
I'm done, thanks

**Comment by geoburdin** [comment]
Should we try to maintain a representative distribution of the number of reviews by country? On a sample of one hundred reviews per application, the selection of these reviews becomes too sensitive to outliers if you look at the non-major country sub-sample
As an example: 70 out of 100 reviews could be in English, but only 5 in German, which does not reflect any patterns in the evaluation of the app by German-speaking users because of the small sample size.

This problem of undersampling can be conditionally solved by expansion of the dataset and collecting a lot more reviews, but I'm not sure if this is required and implied in the task, if geographic distribution is not the feature we would like to extract

**Comment by tanya-ling** [comment]
Hi! It seems a little strange to me that we are not supposed to include rating (the number of stars in the original review) in the data. Is that correct? Should I just remove this information from the data?

**Comment by LastShekel** [comment]
somacruz@bk.ru
Done

**Comment by christina-tkach** [comment]
@geoburdin I agree, but the main objective here is not to collect a non-biased geo distributed sample, so that's alright to stick to the numbers mentioned in the description of the issue. That's also ok to collect a bigger sample if that fits your own goals when solving the task.

**Comment by christina-tkach** [comment]
@tanya-ling that's correct, you can stick to the fields mentioned in the description of the issue

**Comment by vasilchenkoandrey** [comment]
I'm done! Thanks.

**Comment by KhurazovRuslan** [comment]
Sent my solution via e-mail
ruslan.khurazov@gamil.com

**Comment by Athugodage** [comment]
I'm done

**Comment by Rusk-Tram** [comment]
Sent solution via email

**Comment by Nemat-Allah-Aloush** [comment]
Hi! It's expected to use the official API or a third party to collect the reviews from Google Play or App store,  or are we expected to scrap the reviews step by step with `beautifulsoup` library for example? Thanks!

**Comment by HOTPEPE** [comment]
I am done
