### ISSUE TITLE
Accounting system report

### ISSUE THREAD

**Issue by evgenydmitriev** [1712n/challenge#70]
Imagine that you have multiple employees using [Expensify](https://www.expensify.com/) credit cards to make purchases on behalf of various company departments. How would you automate the recording of these transactions to track expenses and to be able to produce department and expense type reports using [Bkper](https://bkper.com/)?

Please email challenge-submission@blockshop.org with your solution, and don't forget to include a link to this issue and attach your resume. Don't hesitate to ask us questions by commenting in this issue or emailing us at challenge-program@blockshop.org

---

### Successful submissions

🎉 @mayavick successfully solved the challenge and was hired by Inca Digital.

**Comment by evgenydmitriev** [comment]
@mayavick successfully solved the challenge and was hired by Inca Digital. Congrats 🎉

**Comment by pvilenkova** [comment]
[accounting system report.pdf](https://github.com/1712n/challenge/files/9413714/accounting.system.report.pdf)

**Comment by credo1** [comment]
Done.

**Comment by lunevaalex** [comment]
Sent to challenge@blockshop.org

**Comment by irina2017992** [comment]
Done and sent ✅
I enjoyed it, thank you
