### ISSUE TITLE
Create promotion campaign

### ISSUE THREAD

**Issue by asyaisakova** [1712n/challenge#74]
We would like to advertise an open position in backend team to backend software engineers of 3 specific mid-size companies in the online banking sector. What tools, technologies, and approaches would you use? How would you evaluate the campaign effectiveness?

**Deliverable:** concise document containing a promotion campaign strategy.

### Additional Resources

* [Challenge Program Wiki](https://github.com/1712n/challenge/)
* [List of available tasks](https://github.com/1712n/challenge/issues)

Please email challenge-submission@blockshop.org with your ideas, and don't forget to include the link to this issue and attach your resume. Don't hesitate to ask us questions by commenting in this issue or emailing us at challenge-program@blockshop.org.

**Comment by ViktoriyaTarasova** [comment]
I sent you an email with my idea.

**Comment by VoskresenskiyDenis** [comment]
Hello!

I emailed you the completed challenge and my CV.
Thank you!

Best regards,
Denis Voskresenskiy

WA +33652680738
Telegram and phone +79869520744
E-mail: [d.voskresenskiy@hotmail.com](mailto:d.voskresenskiy@hotmail.com)

**Comment by IvanRamirez83** [comment]
Hello Asya! 

I just sent you my anwser to this challenge and my resume.
Thank you! 

Best regards,
Ivan.
