### ISSUE TITLE
Reverse-engineer an employer branding campaign

### ISSUE THREAD

**Issue by asyaisakova** [1712n/challenge#75]
Choose any company that you like, analyze their social media content and reverse-engineer their employer branding campaign behind their posts.

**Deliverable:** concise document with clear analysis of employer branding campaign. Good submission often include screenshots and examples of posts.

### Additional Resources

* [Challenge Program Wiki](https://github.com/1712n/challenge/)
* [List of available tasks](https://github.com/1712n/challenge/issues)

Please email challenge-submission@blockshop.org with your solution, and don't forget to include a link to this issue and attach your resume. Don't hesitate to ask us questions by commenting in this issue or emailing us at challenge-program@blockshop.org

**Comment by kravtsovva** [comment]
Sent you an email with my solution. Thanks in advance for reviewing and assessing it.

**Comment by cantarizka** [comment]
Greetings! I've sent my solution to your email. Thank you in advance.

**Comment by MariaMezinova** [comment]
Hi, I have emailed the solution back in September, and was told that I will be considered for upcoming positions. Fast forward to February I still haven’t received any feedback. Did my solution pass your assessment?

**Comment by asyaisakova** [comment]
Hi @MariaMezinova! We did receive your applications and reviewed it carefully.  With its great structure and relevant business examples, it qualifies the admission criteria. Thank you for the efforts and time you put into delivering your report. We're keeping your submission in our talent pool and will reach out to you once we have an opening relevant for your professional level and scope.

**Comment by MariaMezinova** [comment]
Hi, thank you for your response. I appreciate it.Is there any time frame for new job openings? I am now looking for a new job and would really like to apply for one in your company.Thank you in advance.MariaSent from my iPhoneOn 6 Feb 2023, at 14:51, Asya Isakova ***@***.***> wrote:﻿
Hi @MariaMezinova! We did receive your applications and reviewed it carefully.  With its great structure and relevant business examples, it qualifies the admission criteria. Thank you for the efforts and time you put into delivering your report. We're keeping your submission in our talent pool and will reach out to you once we have an opening relevant for your professional level and scope.

**Comment by asyaisakova** [comment]
> Is there any time frame for new job openings?

For now, I don't foresee any job openings in marketing for the upcoming 6 months.  
If it's convenient, you can subscribe to [Hygge Work Instagram](https://www.instagram.com/hygge.work/), as we cross-post job openings and new challenges there.
