### ISSUE TITLE
QA - Identify bots amongst annotators

### ISSUE THREAD

**Issue by alinapark** [1712n/challenge#77]
While crowdsourcing the annotation of our classification datasets, we have seen a number of bots taking up the tasks. We have asked several MTurk people to [annotate texts](https://github.com/1712n/challenge/blob/master/bot-annotators/nlp-challenge.csv) with a true/false value depending on whether the texts are relevant to a topic of Hacker Attack. There's no way to identify the untrustworthy annotators except through their responses. The goal of this issue is to filter out those bots.

#### The Challenge

To participate in the challenge, fork the challenge repository, analyze annotators' responses, create a pull request in your repository with all suspicious annotators removed, and assign this issue assignee as the pull request reviewer. Expanding the pull request description with your methodology can help us better understand your reasoning and evaluate your submission faster. To make sure your submission doesn't get lost, you can also email your pull request link along with your resume and the link to this challenge to [challenge-submission@blockshop.org](mailto:challenge-submission@blockshop.org). Also, don't hesitate to ask us questions by commenting in this issue.

**Comment by geoburdin** [comment]
You can check if there is anything useful
https://colab.research.google.com/drive/1wyLwzRbjzek4-Vg7iZuNxvMJ728caGLa?usp=sharing

**Comment by SvetlanaPek** [comment]
Hello! I sent you an email from svetlana.pekarskikh@gmail.com with a proposed solution.
Have a nice day!

**Comment by lidiaToropova** [comment]
Hi! Sent my solution via email (lydiatoropova@gmail.com). Thanks!

**Comment by bazukas** [comment]
Hello! I have sent a solution via email (azat.khasanshin@gmail.com).

**Comment by MakeRussiaMetalAgain** [comment]
Hi! Asked you a question via email hamitov.tm@phystech.edu

**Comment by achilleess** [comment]
Hello! Sent my solution via email rozhnevn@gmail.com.

**Comment by holyfameeee** [comment]
Hello! Sent my solution via email (holyyyfaaame@gmail.com) :)

**Comment by t0pdog** [comment]
Hi! Sent my solution via email shirikovdmitry@gmail.com. Thanks!
