### ISSUE TITLE
Fix search functionality in an SSG website

### ISSUE THREAD

**Issue by evgenydmitriev** [1712n/challenge#79]
### Problem

There's a broken search functionality in one of our [Hugo websites](https://link.hygge.work/39PUb6m)

![Screenshot 2022-06-23 7 00 19 PM](https://user-images.githubusercontent.com/56804873/175429642-676dac77-a533-4cbf-8e96-f8b4d5dc2fd1.png)

### Deliverable

Submit a pull request that implements search functionality across **all website content** to [this repository](https://link.hygge.work/3QWd6gD). We check all submissions and will reach out to all candidates who successfully fix the errors and enable search across all website articles.

### Additional Resources

* [Challenge Program Wiki](https://github.com/inca-digital/challenge/)
* [List of available tasks](https://github.com/inca-digital/challenge/issues)
* [Inca Digital website](https://inca.digital)

Don't hesitate to ask us questions by commenting in this issue or emailing us at challenge@inca.digital.

**Comment by danisztls** [comment]
It looks like you're using Fuse.js. I used it to develop [lite-search](https://github.com/danisztls/lite-search) and I think I can fix this issue.

**Comment by danisztls** [comment]
Fixed  by [PR](https://github.com/1712n/front-end-challenge/pull/1])

**Comment by weichen123456** [comment]
404 error or 'page not found' error is a Hypertext Transfer Protocol standard response code that indicates the server was unable to find what was requested. This message may also appear when the server is not willing to disclose the requested information or when the content has been deleted.
The simplest and easiest way to fix your 404 error code is to redirect the page to another one. You can perform this task using a 301 redirect. What's 301, you may ask? It's a redirect response code that signals a browser that the content has been transferred to another URL.
My email : developerw707@gmail.com

**Comment by albina-at-inca** [comment]
@evgenydmitriev could you please advise if this task has been fulfilled?

**Comment by weichen123456** [comment]
Hello.
I have finished this task.
I am looking forward to working with you.
Thank you.

**Comment by weichen123456** [comment]
Hello.
I have already finished this task.
I am looking forward to working with you.
I will wait for your response.
Thank you. Regards

**Comment by evgenydmitriev** [comment]
@danisztls and @ryanridnn were the first to correctly solve the challenge. We'll be getting in touch with them to pay the bounty!

**Comment by weichen123456** [comment]
Awesome, thanks!

**Comment by weichen123456** [comment]
Hello.
I am looking forward to hearing from you soon.

**Comment by ryanridnn** [comment]
Hello, there!

I would like to inform you about my payment methods. I would like to
propose a new contract via Upwork with Upwork direct contract, Is that
possible? if not, would you guys send the payment via wise?
