### ISSUE TITLE
Étude de marché

### ISSUE THREAD

**Issue by evgenydmitriev** [1712n/challenge#81]
The goal of this challenge is to compile information on investments in French Blockchain Data and Analytics startups. 

To participate in the challenge, fork the challenge repository and create a pull request with a CSV file that contains investment `year`, `company name`, and `amount` fields. When ready, assign this issue's assignee as the pull request reviewer. Expanding the pull request description with your methodology can help us better understand your reasoning and evaluate your submission faster. To make sure your submission doesn't get lost, you can also email your pull request link along with your resume and the link to this challenge to [challenge-submission@blockshop.org](mailto:challenge-submission@blockshop.org). Also, don't hesitate to ask us questions by commenting in this issue.

**Comment by eric-vs** [comment]
I sent it along. Thank you
Je l'ai envoyé. Merci
