### ISSUE TITLE
Payment processing

### ISSUE THREAD

**Issue by evgenydmitriev** [1712n/challenge#82]
The goal of this challenge is to figure out a way to pay for a hh.ru job post using an international Visa debit card with the least number of steps possible. Please email challenge-submission@blockshop.org with your ideas, and don't forget to include a link to this issue and attach your resume.

### Additional Resources

* [Challenge Program Wiki](https://github.com/1712n/challenge/)
* [List of available tasks](https://github.com/1712n/challenge/issues)

Don't hesitate to ask us questions by commenting in this issue or emailing us at challenge-program@blockshop.org.

## Successful submissions

🎉 @AnastasiaStratienko correctly solved the challenge and got hired by @inca-digital!

**Comment by evgenydmitriev** [comment]
🎉 @AnastasiaStratienko correctly solved the challenge and got hired by @inca-digital! 🍾 Congrats 🍾

**Comment by AnastasiaStratienko** [comment]
Thank you!!!!

**Comment by AESosnovsky** [comment]
Hi! submitted the assignment, hope it'll get your attention:)

**Comment by AESosnovsky** [comment]
Evgeny, does it mean that I need to do another task to apply for a job?

**Comment by evgenydmitriev** [comment]
We have collected enough submissions and will be processing all of them shortly.

**Comment by evgenydmitriev** [comment]
🎉 @GalinaKrukova correctly solved the challenge and got hired by https://github.com/inca-digital! 🍾 Congrats 🍾
