### ISSUE TITLE
Rework hygge.work article

### ISSUE THREAD

**Issue by asyaisakova** [1712n/challenge#83]
Turn [Feedback](https://hygge.work/communication/feedback/) article into a social media post, that would be easy to understand and engaging to read.

**Deliverable:** visual and a text caption for Instagram.

### Additional Resources
* [Hygge Work instagram ](https://www.instagram.com/hygge.work/)
* [Challenge Program Wiki](https://github.com/1712n/challenge/)
* [List of available tasks](https://github.com/1712n/challenge/issues)

Please email challenge-submission@blockshop.org with your ideas, and don't forget to include the link to this issue and attach your resume. Don't hesitate to ask us questions by commenting in this issue or emailing us at challenge-program@blockshop.org.

---

### Successful submissions

🎉  @yuliakondr successfully solved the challenge and was hired by Inca Digital.

**Comment by NickPiter** [comment]
https://user-images.githubusercontent.com/114153824/191732999-97f32f73-51e7-49be-a421-163135deb708.MOV

**Comment by daniilfursa** [comment]
I've sent you an email with my solution. Waiting for your feedback :)

**Comment by seom2001** [comment]
my bad, but I don't understand exactly what is the task to be done

**Comment by asyaisakova** [comment]
> my bad, but I don't understand exactly what is the task to be done

Read the [Feedback article](https://hygge.work/communication/feedback/), think of a way to present its content in social media, and send us your idea in the form of an Instagram post.

**Comment by sanjakhmedov** [comment]
I have sent my solution to email and my answer was not correct, it is okay if I try one more time?

**Comment by asyaisakova** [comment]
> I have sent my solution to email and my answer was not correct, it is okay if I try one more time?

You can try one more time or look through other [marketing issues](https://github.com/1712n/challenge/issues?q=is%3Aissue+is%3Aopen+label%3Amarketing)

**Comment by asyaisakova** [comment]
🎉 @yuliakondr successfully solved the challenge and was hired by Inca Digital.
