### ISSUE TITLE
MarketCapBot - Automate posting on Twitter

### ISSUE THREAD

**Issue by sofiasedlova** [1712n/challenge#86]
The goal of this challenge is to build a Python [Twitter bot](https://twitter.com/CryptoCapBot) using GitHub Actions and MongoDB.

## Required functionality

A Python function will compose and post a tweet with the latest values from [MongoDB time series](https://www.mongodb.com/docs/manual/core/timeseries-collections/) collections using the logic described below.

## Algo

1. query `ohlcv_db` for the top 100 `pair`s by compound `volume`
1. query `posts_db` for the latest documents corresponding to those 100 `pair`s
1. sort results by the oldest `timestamp` to find the pairs that haven't been posted for a while, then corresponding `volume` to find the biggest markets among them and select the `pair_to_post`
1. compose `message_to_post` for the `pair_to_post` with corresponding latest `volume`s by `market` values from `ohlcv_db` using this example:
   ```
   Top Market Venues for BTC-USDC:
   Binance 30.10%
   Coinbase 20.20%
   Kraken 10.30%
   Bitstamp 5.40%
   Huobi 2.50%
   Others 31.5%
   ```
1. keep similar tweets in one thread. if `pair_to_post` tweets already exists in `posts_db`, post tweet to the corresponding Twitter thread. else, post a new tweet.
1. add your `message_to_post` to `posts_db`

## Important notes

- **To start send your resume and a link to this challenge to [challenge-submission@blockshop.org](mailto:challenge-submission@blockshop.org). Then we'll add you to collaborators and share all necessary credentials.**
- Create your own branch in this [repository](https://github.com/1712n/twitter-bot-challenge#twitter-bot-challenge) and use iterative approach. We want to see your progress as much as we want to see the result.
- Think about tests and error handling. We will be stress testing your code by corrupting databases and revoking access permissions.
- Limit Twitter API usage, rely on MongoDB to save the state.
- Leverage MongoDB time series optimizations to save computational resources.

Find all other technical instructions [here](https://github.com/1712n/twitter-bot-challenge#twitter-bot-challenge). 
Feel free to ask questions in the comment section below, or email challenge@blockshop.org. As soon as we get a good enough solution from a candidate, we start the interviewing process. If you are ready with your branch, create a pull request and assign it to us for review.

**Comment by evgenydmitriev** [comment]
Please email challenge@blockshop.org if you have questions that can't be resolved in the comments section of the issue.

**Comment by sofiasedlova** [comment]
@Vlhss we are always searching for talents! that's why we are feeding the challenge program community with interesting tasks. this challenge task is built in the hiring pipeline. read [general rules](https://github.com/1712n/challenge#general-rules) to get more information on the pay-out.

**Comment by jalmonter** [comment]
Hey @sofiasedlova I'd like to give this a try. Can you please assign to me?

**Comment by aleksandra1998e** [comment]
Hey @sofiasedlova I'd like to give this a try too. I send my resume and a link to this challenge to email. So, I decide to write here too.

**Comment by xksd** [comment]
Hi @sofiasedlova,
I would like to participate in this challenge. Just sent my CV to an email.
Exciting task, can't wait to start!

**Comment by kateusanova** [comment]
Hi @sofiasedlova, I'd like to give it a try too. Just sent my CV and link to this challenge to email.

**Comment by Saa4s** [comment]
Hello @sofiasedlova, i wanna give this task a try, too!

**Comment by p17m0** [comment]
i don't want to do it! I don't give this task a try!

**Comment by ivan-gorin** [comment]
Hi @sofiasedlova , what exactly does "top 100 pairs by compound volume" mean? Just sorting all documents by volume or should we aggregate by pairs first?

**Comment by sofiasedlova** [comment]
> Just sorting all documents by volume or should we aggregate by pairs first?

exactly

> should we use all documents or only the most recent, for example the last hour?

this doesn't affect the general logic of the task, choose your approach wisely

**Comment by ivan-gorin** [comment]
> > Just sorting all documents by volume or should we aggregate by pairs first?
> 
> 
> 
> exactly

So, which approach is correct, the first one or the second one?

**Comment by sofiasedlova** [comment]
1. query volume sum by `pair.id`

**Comment by sofiasedlova** [comment]
A reminder for all participants and others who still hesitate! Give this challenge a try, demonstrate your skills in the best light and get your deserved reward!

**Comment by mirmozavr** [comment]
> A reminder for all participants and others who still hesitate! Give this challenge a try, demonstrate your skills in the best light and get your deserved reward!

What's the reward?

**Comment by sofiasedlova** [comment]
@mirmozavr find all information in the labels section and go through the [general rules](https://github.com/1712n/challenge#general-rules)

**Comment by DamirShamsutdinov** [comment]
I want to try solve this case too

**Comment by sofiasedlova** [comment]
cool! to start send your resume and a link to this challenge to [challenge-submission@blockshop.org](mailto:challenge-submission@blockshop.org). then we'll add you to collaborators and share all necessary credentials.

**Comment by mlyaaana** [comment]
Hi, @sofiasedlova, I'd like to give this a try too. I send my resume and a link to this challenge to email.

**Comment by sofiasedlova** [comment]
thanks everyone for submitting to this challenge! by the end of this week we'll announce the winner. this means that we are no longer adding new outside collaborators. however, our team is waiting for the last changes to the branches with solutions from the ones who have already got access.

**Comment by sofiasedlova** [comment]
Hey guys! It was a pleasure to see considerable attention to our Challenge Program and this Python task specifically.

Throughout this round, more than 60 users were added as outside collaborators, 30+ branches were created, 17 pull requests were reviewed. You have differently approached this problem using elegant aggregations, showing off OOP native style and unit tests.

Let me announce the winner of the challenge. The most pythonic solution was submitted by @eg-mart! 🧠

**Comment by BorisThereIs** [comment]
My congratulations to the winner. Thanks for this challenge. I've learned some new things. It was useful experience. Best wishes to all participants )

**Comment by eg-mart** [comment]
Thank you for this interesting challenge! It was a pleasure to do, and the financial reward was quite a nice bonus) I really am looking forward to further cooperation with Inca Digital. I wish all other participants to keep trying and to succeed eventually!
