### ISSUE TITLE
Binance order book metrics

### ISSUE THREAD

**Issue by alekseypolukeev** [1712n/challenge#89]
## Overview
There is a working Kotlin application that requests order books for all Binance symbols (financial instruments) and calculates the average volumes for asks and bids, but it does it inefficiently.

The first problem that it takes too long to retrieve order books one by one. Even after the fix, the calculator is not ready to become a real time streaming application as it keeps all the state in memory to compute the average volumes.

We expect the order book metrics calculator to be improved to fit application timeout and reduce memory consumption.

More details can be found in the challenge [repository](https://github.com/1712n/backend-challenge).

## Required skills
- Java/Kotlin programming language
- understanding of stream and reactive programming approaches

## Additional Resources

* [Challenge Program Wiki](https://github.com/1712n/challenge/)
* [List of available tasks](https://github.com/1712n/challenge/issues)
* [Inca Digital website](https://inca.digital)

**Comment by alekseypolukeev** [comment]
Thanks everyone for participating in our Challenge Program and this Java/Kotlin task specifically.

Throughout this round, more than 10 users provided their solutions. We were happy to see so many different approaches to solve this problem.

Let me announce the winner of the challenge who successfully passed the recruitment process first and got an offer - @hweawer! 🧠

**Comment by Preposterone** [comment]
Damn, that was fast, is it possible to see the winning repository? @hweawer @alekseypolukeev
