### ISSUE TITLE
Sensitive information in GitHub

### ISSUE THREAD

**Issue by evgenydmitriev** [1712n/challenge#91]
Developers often unintentionally share sensitive information in GitHub issue tracker, discussions, or pull request comments. An example of such information can be contact information of clients and partners.

To participate in this challenge, fork the challenge repository and create a pull request with a piece of code that automatically checks for contact information (let's use [this partner of ours](https://www.lisn.upsaclay.fr/recherche/departements-et-equipes/sciences-et-technologies-des-langues/information-langue-ecrite-et-signee-iles-2-2-2-2/membres-iles/) as an example) being shared in GitHub issue tracker and redacts the sensitive parts or notifies someone to do it. When ready, request a review from this issue assignee. Expanding the pull request description with your methodology can help us better understand your reasoning and evaluate your submission faster. To make sure your submission doesn't get lost, you can also email your pull request link along with your resume and the link to this challenge to [challenge-submission@blockshop.org](mailto:challenge-submission@blockshop.org). Also, don't hesitate to ask us questions by commenting in this issue.

<details><summary>💡Hint</summary>You can complete this challenge with 0 coding experience by carefully thinking through the problem and reading GitHub documentation. The only successful submission we had <a href="https://www.instagram.com/p/CpCTZEKtjeJ/">came from the candidate</a> who didn't know how to code.</details>

**Comment by AbduazizZiyodov** [comment]
Hello👋
I decided to accept this challenge 😁
I need to clarify something for myself. We have comments on GitHub issues, discussions and pull requests. I need to implement such functionality that checks comments for sensitive information.

Is it right? Or is there anything missing?

**Comment by evgenydmitriev** [comment]
@AbduazizZiyodov everything is correct, just keep in mind that this mostly a business intelligence challenge with multiple 0 code solutions out there.  We are not trying to challenge developers here.

**Comment by AbduazizZiyodov** [comment]
Thanks, understood. So I can solve it with either code or zero code. However, because it is interesting for me also,  I wanna provide a solution with code.
And then, I can open a pull request, right?
