### ISSUE TITLE
Service to deploy NLP models for inference

### ISSUE THREAD

**Issue by alinapark** [1712n/challenge#98]
### Overview 
Create a service that deploys five NLP models for inference, then receives messages through an exposed POST API endpoint, and finally returns inference results (of all five models) in a single response body.
Expected deliverable is a **service packed in the Docker image**.

Your service could be a well-configured framework or a self-made API server; use any ML model deployment tool you see fit. There's no language limitation. The most important here is the reusability of a final project.

All submissions will be deployed on a `g4dn.2xlarge` [instance](https://aws.amazon.com/ec2/instance-types/g4/), and the assessment will be performance (mainly, throughput)-based

**More details in the challenge [repository](https://github.com/1712n/infra-challenge/)**

--- 

## Additional Resources

* [Challenge Program Wiki](https://github.com/1712n/challenge/)
* [List of available tasks](https://github.com/1712n/challenge/issues)
* [Inca Digital website](https://inca.digital)

**Comment by khushpatel2002** [comment]
Hello, For the challenge, is it allowd to change the format of model mentioned. from pytorch to tensorflow / onnx ?

**Comment by alinapark** [comment]
@khushpatel2002 yes, feel free to use either

**Comment by khushpatel2002** [comment]
@alinapark Thank you for your reply.

**Comment by mizykov** [comment]
@alinapark, hello!
Is this challenge still relevant?
